internal_locale: en 
base_locale: fr 
locales:
- en
- fr
data:
  adapter: I18n::Tasks::Data::FileSystem
  read:
  - config/locales/%{locale}.yml
  - config/locales/my_%{locale}.yml
  write:
  - config/locales/%{locale}.yml
search:
  scanner: I18n::Tasks::Scanners::PatternWithScopeScanner
  relative_roots:
  - app/views
  paths:
  - app/
  exclude:
  - "*.jpg"
  - "*.png"
  - "*.gif"
  - "*.svg"
  - "*.ico"
  - "*.eot"
  - "*.ttf"
  - "*.woff"
  - "*.woff2"
  - "*.pdf"
  ignore_lines:
    rb: "^\\s*#(?!\\si18n-tasks-use)"
    haml: "^\\s*-\\s*#(?!\\si18n-tasks-use)"
    slim: "^\\s*(?:-#|/)(?!\\si18n-tasks-use)"
    coffee: "^\\s*#(?!\\si18n-tasks-use)"
    erb: "^\\s*<%\\s*#(?!\\si18n-tasks-use)"
